apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/nati-cardoso-machado-gmail-com/teste4-natalia:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/nati-cardoso-machado-gmail-com/teste4-natalia:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: teste4-natalia
        chartPath: charts/teste4-natalia
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/nati-cardoso-machado-gmail-com/teste4-natalia"
          image.tag: "{{.DIGEST_HEX}}"
